version: '3.8' 


volumes:
  prometheus_data:

  grafana_data:

services:

  
  prometheus-bot:
    container_name: prometheus-bot
    image: prometheus-bot:0.0.1
    volumes:
      - ./telegrambot/:/etc/telegrambot/
      - ./telegrambot/config.yaml:/config.yaml  
    ports:
      - 9087:9087
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    expose:
      - 9100

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager:/opt/alertmanager
    command:
      - '--config.file=/opt/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
           - ./prometheus:/etc/prometheus
           - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


  
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
            - ./grafana:/etc/grafana/provisioning/datasources
            - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
