global:
  scrape_interval: 10s
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
        

rule_files:
 - rules.yml

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "node"
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
 
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "alertmanager"
    scrape_interval: 5s
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: "jenkins"
    metrics_path: /prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8080']
