groups:
 - name: jenkinsandhoststats
   rules:
   - alert: InstanceDown
     expr: up{job="jenkins"} == 0
   - alert: HostOutOfMemory
     expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 30
     for: 5m
     labels:
       severity: warning
     annotations:
       summary: "Host out of memory (instance {{ $labels.instance }})"
       description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


   - alert: HostOutOfDiskSpace
     expr: (node_filesystem_avail_bytes{mountpoint="/"}  * 100) / node_filesystem_size_bytes{mountpoint="/"} < 50
     for: 1s
     labels:
       severity: warning
     annotations:
       summary: "Host out of disk space (instance {{ $labels.instance }})"
       description: "Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


   - alert: HostHighCpuLoad
     expr: (sum by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[5m]))) > 30
     for: 5m
     labels:
       severity: warning
     annotations:
       summary: "Host high CPU load (instance {{ $labels.instance }})"
       description: "CPU load is > 30%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
